/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"

#define GPIOAEN (1U<<0)
#define GPIOCEN (1U<<2)

#define PIN5 (1U<<5)
#define PIN13 (1U<<13)

#define LED_PIN PIN5
#define BTN_PIN PIN13

int main(void){
	RCC->AHB1ENR |=GPIOAEN;
	RCC->AHB1ENR |=GPIOCEN;

	GPIOA->MODER |=(1U<<10);
	GPIOA->MODER &=~(1U<<11);

	GPIOC->MODER &=~(1U<<26);
	GPIOC->MODER &=~(1U<<27);

	while(1){
		if ((GPIOC->IDR & BTN_PIN) == 0U){
			GPIOA->BSRR = LED_PIN;
		}
		else {
			GPIOA->BSRR = (1U<<21);
		}
	}
}
